# Generated by Django 2.1 on 2019-06-19 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='number',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='value',
            new_name='stars',
        ),
    ]
